"""empty message

Revision ID: 988176be6df6
Revises: bbac5b06105c
Create Date: 2024-11-06 21:49:43.877574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988176be6df6'
down_revision = 'bbac5b06105c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
